### ISSUE TITLE
All components in dark mode

### ISSUE THREAD

**Issue by Samrridh** [merakiui/merakiui#91]
I recently used your service. No doubt the components are great but all of them are being implemented in dark mode by default, and i cant get around to change it to light mode. I dont think the problem is at my end, can the devs or someone else help me

**Comment by khatabwedaa** [comment]
Hey @Samrridh, sorry for the confusion. The issue occurred because Tailwind CSS v3 automatically generates dark mode classes and uses your system theme to set the tailwind applied theme. If you have dark mode enabled as your system theme, Tailwind will apply dark mode classes by default.

To fix this issue, you can disable this behavior by adding the `darkMode` variable in your Tailwind config file.

```js
module.exports = {
  darkMode: 'class',
  // ...
}
```
